// This file is @generated by prost-build.
/// 一个 ImageSpec 是一个有序的数组，服务器按照 spec 的顺序处理
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImageSpec {
    #[prost(message, repeated, tag = "1")]
    pub specs: ::prost::alloc::vec::Vec<Spec>,
}
/// 处理图片改变大小
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resize {
    #[prost(uint32, tag = "1")]
    pub width: u32,
    #[prost(uint32, tag = "2")]
    pub height: u32,
    #[prost(enumeration = "resize::ResizeType", tag = "3")]
    pub rtype: i32,
    #[prost(enumeration = "resize::SampleFilter", tag = "4")]
    pub filter: i32,
}
/// Nested message and enum types in `Resize`.
pub mod resize {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ResizeType {
        Normal = 0,
        SeamCarve = 1,
    }
    impl ResizeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                ResizeType::Normal => "NORMAL",
                ResizeType::SeamCarve => "SEAM_CARVE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NORMAL" => Some(Self::Normal),
                "SEAM_CARVE" => Some(Self::SeamCarve),
                _ => None,
            }
        }
    }
    ///   采样滤波
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SampleFilter {
        Undefined = 0,
        Nearest = 1,
        Triangle = 2,
        CatmullRom = 3,
        Gaussian = 4,
        Lanczos3 = 5,
    }
    impl SampleFilter {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                SampleFilter::Undefined => "UNDEFINED",
                SampleFilter::Nearest => "NEAREST",
                SampleFilter::Triangle => "TRIANGLE",
                SampleFilter::CatmullRom => "CATMULL_ROM",
                SampleFilter::Gaussian => "GAUSSIAN",
                SampleFilter::Lanczos3 => "LANCZOS3",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNDEFINED" => Some(Self::Undefined),
                "NEAREST" => Some(Self::Nearest),
                "TRIANGLE" => Some(Self::Triangle),
                "CATMULL_ROM" => Some(Self::CatmullRom),
                "GAUSSIAN" => Some(Self::Gaussian),
                "LANCZOS3" => Some(Self::Lanczos3),
                _ => None,
            }
        }
    }
}
/// 剪裁
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Crop {
    #[prost(uint32, tag = "1")]
    pub x1: u32,
    #[prost(uint32, tag = "2")]
    pub y1: u32,
    #[prost(uint32, tag = "3")]
    pub x2: u32,
    #[prost(uint32, tag = "4")]
    pub y2: u32,
}
/// 水平翻转
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fliph {}
/// 垂直翻转
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Flipv {}
/// 对比度
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Contrast {
    #[prost(float, tag = "1")]
    pub contrast: f32,
}
/// 滤镜
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Filter {
    #[prost(enumeration = "filter::Filter", tag = "1")]
    pub filter: i32,
}
/// Nested message and enum types in `Filter`.
pub mod filter {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Filter {
        Unspecified = 0,
        Oceanic = 1,
        Islands = 2,
        Marine = 3,
        Seagreen = 4,
        Flagblue = 5,
        Liquid = 6,
        Diamante = 7,
        Radio = 8,
        Twenties = 9,
        Rosetint = 10,
        Mauve = 11,
        Bluechrome = 12,
        Vintage = 13,
        Perfume = 14,
        /// more: <https://docs.rs/photon-rs/0.3.1/photon_rs/filters/fn.filter.html>
        Serenity = 15,
    }
    impl Filter {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Filter::Unspecified => "UNSPECIFIED",
                Filter::Oceanic => "OCEANIC",
                Filter::Islands => "ISLANDS",
                Filter::Marine => "MARINE",
                Filter::Seagreen => "SEAGREEN",
                Filter::Flagblue => "FLAGBLUE",
                Filter::Liquid => "LIQUID",
                Filter::Diamante => "DIAMANTE",
                Filter::Radio => "RADIO",
                Filter::Twenties => "TWENTIES",
                Filter::Rosetint => "ROSETINT",
                Filter::Mauve => "MAUVE",
                Filter::Bluechrome => "BLUECHROME",
                Filter::Vintage => "VINTAGE",
                Filter::Perfume => "PERFUME",
                Filter::Serenity => "SERENITY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNSPECIFIED" => Some(Self::Unspecified),
                "OCEANIC" => Some(Self::Oceanic),
                "ISLANDS" => Some(Self::Islands),
                "MARINE" => Some(Self::Marine),
                "SEAGREEN" => Some(Self::Seagreen),
                "FLAGBLUE" => Some(Self::Flagblue),
                "LIQUID" => Some(Self::Liquid),
                "DIAMANTE" => Some(Self::Diamante),
                "RADIO" => Some(Self::Radio),
                "TWENTIES" => Some(Self::Twenties),
                "ROSETINT" => Some(Self::Rosetint),
                "MAUVE" => Some(Self::Mauve),
                "BLUECHROME" => Some(Self::Bluechrome),
                "VINTAGE" => Some(Self::Vintage),
                "PERFUME" => Some(Self::Perfume),
                "SERENITY" => Some(Self::Serenity),
                _ => None,
            }
        }
    }
}
/// 水印
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Watermark {
    #[prost(uint32, tag = "1")]
    pub x: u32,
    #[prost(uint32, tag = "2")]
    pub y: u32,
}
/// 混合
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Blend {
    #[prost(enumeration = "blend::Blend", tag = "1")]
    pub blend: i32,
}
/// Nested message and enum types in `Blend`.
pub mod blend {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Blend {
        Overlay = 0,
        Over = 1,
        Atop = 2,
        Xor = 3,
        Multiply = 4,
        Burn = 5,
        SoftLight = 6,
        HardLight = 7,
        Difference = 8,
        Lighten = 9,
        Darken = 10,
        Dodge = 11,
        Plus = 12,
        Exclusion = 13,
    }
    impl Blend {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Blend::Overlay => "OVERLAY",
                Blend::Over => "OVER",
                Blend::Atop => "ATOP",
                Blend::Xor => "XOR",
                Blend::Multiply => "MULTIPLY",
                Blend::Burn => "BURN",
                Blend::SoftLight => "SOFT_LIGHT",
                Blend::HardLight => "HARD_LIGHT",
                Blend::Difference => "DIFFERENCE",
                Blend::Lighten => "LIGHTEN",
                Blend::Darken => "DARKEN",
                Blend::Dodge => "DODGE",
                Blend::Plus => "PLUS",
                Blend::Exclusion => "EXCLUSION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OVERLAY" => Some(Self::Overlay),
                "OVER" => Some(Self::Over),
                "ATOP" => Some(Self::Atop),
                "XOR" => Some(Self::Xor),
                "MULTIPLY" => Some(Self::Multiply),
                "BURN" => Some(Self::Burn),
                "SOFT_LIGHT" => Some(Self::SoftLight),
                "HARD_LIGHT" => Some(Self::HardLight),
                "DIFFERENCE" => Some(Self::Difference),
                "LIGHTEN" => Some(Self::Lighten),
                "DARKEN" => Some(Self::Darken),
                "DODGE" => Some(Self::Dodge),
                "PLUS" => Some(Self::Plus),
                "EXCLUSION" => Some(Self::Exclusion),
                _ => None,
            }
        }
    }
}
/// 一个 spec 可以包含上述的处理方式之一
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Spec {
    #[prost(oneof = "spec::Data", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub data: ::core::option::Option<spec::Data>,
}
/// Nested message and enum types in `Spec`.
pub mod spec {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        Resize(super::Resize),
        #[prost(message, tag = "2")]
        Crop(super::Crop),
        #[prost(message, tag = "3")]
        Flipv(super::Flipv),
        #[prost(message, tag = "4")]
        Fliph(super::Fliph),
        #[prost(message, tag = "5")]
        Contrast(super::Contrast),
        #[prost(message, tag = "6")]
        Filter(super::Filter),
        #[prost(message, tag = "7")]
        Watermark(super::Watermark),
        #[prost(message, tag = "8")]
        Blend(super::Blend),
    }
}
