[package]
name = "xunmi-py"
version = "0.1.0"
edition = "2024"

[lib]
name = "xunmi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
serde_json = "1.0.133"
xunmi = "0.2.1"

[build-dependencies]
pyo3-build-config = "0.23.1"
